version: '3'
services:
  server:    
    build: ./server
    volumes:
      - ./server:/usr/src/app
    environment: 
      CONNECTION_STRING: mongodb://root:secret@db:27017  
      ASPNETCORE_URLS: http://+:8000
    depends_on: 
      - db
    restart: unless-stopped
  
  db:
    build: ./db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    restart: unless-stopped
  
  www:
    build: ./www
    volumes:
      - ./www:/usr/src/app     
    restart: unless-stopped
  
  proxy:
    build: ./proxy
    ports: 
      - "8080:80"
    depends_on: 
      - www
      - server  
    restart: unless-stopped
    